export const ACTION_TYPES = {
  sidebar: {
    SIDEBAR_ADD_CATEGORY: 'SIDEBAR_ADD_CATEGORY',
  },
  modals: {
    OPEN_SIDEBAR_ADD_CATEGORY: 'OPEN_OR_CLOSE_SIDEBAR_ADD_CATEGORY',
    CLOSE_SIDEBAR_ADD_CATEGORY: 'CLOSE_OR_CLOSE_SIDEBAR_ADD_CATEGORY'
  }
}
